title: BDR927的博客
description: 个人学习随笔与技术笔记
url: "https://BDR927.github.io"
baseurl: ""
remote_theme: cotes2020/jekyll-theme-chirpy
timezone: Asia/Shanghai

paginate: 10
paginate_path: "/page/:num/"
markdown: kramdown
post_date_format: "%Y-%m-%d"

author:
  name: BDR927
  email: test@xxx.com

navbar:
  links:
    - name: 首页
      url: /
    - name: 分类
      url: /categories/
    - name: 标签
      url: /tags/
    - name: 关于
      url: /about/

robots: allow
sitemap: true
comments:
  active: false
code_block:
  line_numbers: true
